# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            'Mark Kolev'
tagline:          'Welcome to my Website!'
description:      'Heres a bit of placeholder data'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

#gems: [jekyll-paginate]
#gems: [jekyll-gist]
#gems: [pygments.rb]


#gems: [jekyll-paginate]
#paginate:         5

gems:

- jekyll-gist
- jekyll-paginate
- pygments

paginate: 5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mnkolev
